-- 0101_message_translations: on-demand, cached translation of staff chat
-- messages into a viewer's own language (the Telegram-style "Translate"
-- action on a message or a whole conversation).
--
-- Cached rather than translated fresh on every view for the same reason
-- entity_translations and page translations are cached (migrations 0067/
-- 0068): a message never changes after it is sent, so translating it twice
-- would just be paying the Workers AI cost and latency again for the exact
-- same output. No `auto_translated` flag here (unlike entity_translations)
-- -- these are never hand-edited, only ever regenerated by re-running the
-- same deterministic translate call, so there is nothing to distinguish.
PRAGMA foreign_keys = ON;

CREATE TABLE message_translations (
  message_id TEXT NOT NULL,
  locale TEXT NOT NULL,
  translated_body TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (message_id, locale),
  FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);
