import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("robots.txt", "routes/robots.txt.ts"),
  route("sitemap.xml", "routes/sitemap.xml.ts"),
  route("sitemaps/products.xml", "routes/sitemaps.products.xml.ts"),
  route("sitemaps/categories.xml", "routes/sitemaps.categories.xml.ts"),
  route("sitemaps/pages.xml", "routes/sitemaps.pages.xml.ts"),
  route("sitemaps/blog.xml", "routes/sitemaps.blog.xml.ts"),
  route("sitemaps/recipes.xml", "routes/sitemaps.recipes.xml.ts"),
  route("sitemaps/farms.xml", "routes/sitemaps.farms.xml.ts"),
  route("sitemaps/discussions.xml", "routes/sitemaps.discussions.xml.ts"),
  route("llms.txt", "routes/llms.txt.ts"),
  route("shop", "routes/shop.tsx"),
  route("seasonal", "routes/seasonal.tsx"),
  route("category/:slug", "routes/category.tsx"),
  route("product/:slug", "routes/product.tsx"),
  route("search", "routes/search.tsx"),
  route("farms", "routes/farms.tsx"),
  route("farms/:slug", "routes/farm.tsx"),
  route("recipes", "routes/recipes.tsx"),
  route("recipes/submit", "routes/submit-recipe.tsx"),
  route("recipes/:slug", "routes/recipe.tsx"),
  route("blog", "routes/blog.tsx"),
  route("blog/submit", "routes/submit-blog.tsx"),
  route("blog/:slug", "routes/article.tsx"),
  route("community", "routes/community.tsx"),
  route("community/new", "routes/new-discussion.tsx"),
  route("community/:id", "routes/discussion.tsx"),
  route("standards", "routes/standards.tsx"),
  route("about", "routes/about.tsx"),
  route("delivery", "routes/delivery.tsx"),
  route("returns", "routes/returns.tsx"),
  route("contact", "routes/contact.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("help", "routes/help.tsx"),
  route("cart", "routes/cart.tsx"),
  route("checkout", "routes/checkout.tsx"),
  route("payment/razorpay", "routes/razorpay-payment.tsx"),
  route("payment/paypal", "routes/paypal-payment.tsx"),
  route("account", "routes/account.tsx"),
  route("account/orders/:reference", "routes/order.tsx"),
  route("account/submissions", "routes/my-submissions.tsx"),
  route("account/submissions/:id/edit", "routes/edit-submission.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
