import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("robots.txt", "routes/robots.txt.ts"),
  route("sitemap.xml", "routes/sitemap.xml.ts"),
  route("llms.txt", "routes/llms.txt.ts"),
  route("shop", "routes/shop.tsx"),
  route("seasonal", "routes/seasonal.tsx"),
  route("category/:slug", "routes/category.tsx"),
  route("product/:slug", "routes/product.tsx"),
  route("search", "routes/search.tsx"),
  route("farms", "routes/farms.tsx"),
  route("farms/:slug", "routes/farm.tsx"),
  route("recipes", "routes/recipes.tsx"),
  route("recipes/:slug", "routes/recipe.tsx"),
  route("journal", "routes/journal.tsx"),
  route("journal/:slug", "routes/article.tsx"),
  route("standards", "routes/standards.tsx"),
  route("about", "routes/about.tsx"),
  route("delivery", "routes/delivery.tsx"),
  route("returns", "routes/returns.tsx"),
  route("contact", "routes/contact.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("help", "routes/help.tsx"),
  route("cart", "routes/cart.tsx"),
  route("checkout", "routes/checkout.tsx"),
  route("payment/razorpay", "routes/razorpay-payment.tsx"),
  route("payment/paypal", "routes/paypal-payment.tsx"),
  route("account", "routes/account.tsx"),
  route("account/orders/:reference", "routes/order.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
