"""The canonical question bank -- the data half of the classifier.

Tier B matches an incoming message against these phrasings rather than
generating anything, so recall is a function of how well this file covers the
ways real customers write. It is deliberately a plain data module: adding a
phrasing is a one-line change with no code to touch, and every routing decision
the bot makes can be traced back to a specific line here.

**This file is where accuracy comes from.** Tuning the similarity maths in
`classifier.py` was measured against a held-out set of ninety-odd real
phrasings and moved routing accuracy by roughly two percent across every
parameter combination tried. Adding phrasings here moved it by twenty. If the
bot is getting something wrong, the fix is almost always a line in this file,
not a change to the scorer.

Writing rules, so later additions stay consistent with the existing entries:

* **Phrase it the way a customer types it**, not the way a policy document
  words it -- "where is my stuff" belongs here, "order fulfilment enquiry" does
  not.
* **Cover the register range** for each intent: terse ("track order"),
  conversational ("can you tell me where my order has got to"), and frustrated
  ("still no sign of my order"). Customers who are annoyed write differently
  from customers who are browsing, and the annoyed ones are the ones it costs
  most to misroute.
* **Keep intents lexically apart.** Two intents whose phrasings share most of
  their content words will both score mid-band and neither will clear the gate,
  which sends a perfectly answerable question to a human. When two intents are
  genuinely close (`refund_status` vs `return_status`, `return_policy` vs
  `return_start`), lean on the word that actually separates them and let
  `patterns.py` carry the phrasings where one token decides it outright.
* **Do not paraphrase an existing line.** Two near-identical phrasings add
  nothing and dilute the IDF weighting that makes distinctive words count.

Spelling is British/Indian English to match the storefront's own copy, and
common misspellings are left out on purpose -- character-bigram scoring in
`classifier.py` already absorbs those without bloating the bank.
"""

from __future__ import annotations

# intent key -> the ways customers ask it.
PHRASEBOOK: dict[str, tuple[str, ...]] = {
    # ---------------------------------------------------------------- orders
    "order_status": (
        "where is my order",
        "what is the status of my order",
        "track my order",
        "can you tell me where my order is",
        "has my order been dispatched yet",
        "is my order on its way",
        "any update on my order",
        "what is happening with my order",
        "order tracking details",
        "when will my order be delivered",
        "has my order shipped",
        "where has my order got to",
        "is my parcel out for delivery",
        "check the progress of my order",
        "did my order go out today",
        "what stage is my order at",
        "give me an update on my delivery",
        "is my package on the way to me",
    ),
    "order_list": (
        "show me my orders",
        "what have I ordered recently",
        "list my past orders",
        "my order history",
        "what did I buy last time",
        "how many orders have I placed",
        "see all my previous orders",
        "everything I have ordered from you",
        "pull up my order history",
        "what orders do I have open",
        "my recent purchases",
    ),
    "order_items": (
        "what is in my order",
        "which products are in my last order",
        "what did I order",
        "show me the items in my order",
        "what does my order contain",
        "list the products on my order",
        "remind me what I put in that order",
        "what is inside the box coming to me",
    ),
    "order_cancel": (
        "I want to cancel my order",
        "how do I cancel an order",
        "can I cancel my order now",
        "please cancel this order",
        "is it too late to cancel my order",
        "I changed my mind about my order",
        "stop my order from being sent",
        "call off the order I placed",
        "I do not want the order any more",
        "scrap that order for me",
    ),
    "order_invoice": (
        "I need an invoice for my order",
        "where can I download my bill",
        "send me the receipt for my order",
        "do you provide a gst invoice",
        "I need a tax invoice",
        "how do I get a copy of my bill",
        "can I have a receipt for what I paid",
        "invoice for accounting purposes",
    ),
    "order_change_address": (
        "I need to change my delivery address",
        "can I update the address on my order",
        "I entered the wrong address",
        "please send my order to a different address",
        "change the shipping address on my order",
        "I moved house can you redirect my order",
        "my address on the order is incorrect",
        "can the order be sent somewhere else",
        "wrong pin code on my order please fix it",
        "divert my parcel to my office instead",
    ),
    "order_missing_item": (
        "an item is missing from my order",
        "my order arrived incomplete",
        "one product was not in the box",
        "I did not receive everything I ordered",
        "part of my order is missing",
        "the box was short of one item",
        "only half my order turned up",
        "something I paid for was not included",
        "two items ordered only one delivered",
    ),
    "order_damaged_item": (
        "my order arrived damaged",
        "the product was broken when it arrived",
        "the packaging was crushed",
        "the item came smashed",
        "my delivery was damaged in transit",
        "the produce arrived bruised and unusable",
        "the jar was cracked and leaking",
        "everything was squashed in the box",
        "the contents were spilled everywhere",
        "poor packing and the goods suffered",
    ),
    "order_wrong_item": (
        "I received the wrong item",
        "you sent me the wrong product",
        "this is not what I ordered",
        "the wrong thing was delivered",
        "I got someone else order",
        "the product delivered does not match my order",
        "wrong variant was sent to me",
        "I ordered one thing and got another",
    ),
    "order_not_arrived": (
        "my order never arrived",
        "the tracking says delivered but I have nothing",
        "I have not received my order",
        "my order is missing",
        "no sign of my delivery",
        "the courier marked it delivered but it is not here",
        "marked as delivered but nobody came",
        "my parcel has gone missing in transit",
        "the delivery never reached my address",
    ),
    "order_delayed": (
        "my order is late",
        "why is my order taking so long",
        "my delivery is delayed",
        "it has been a week and nothing has come",
        "my order is past the expected date",
        "this is much slower than promised",
        "the delivery date has come and gone",
        "why has my order not moved for days",
        "still waiting far longer than you said",
    ),
    # --------------------------------------------------------------- returns
    "return_policy": (
        "what is your return policy",
        "can I return something",
        "how many days do I have to return an item",
        "are returns accepted",
        "what are the conditions for returning a product",
        "is there a return window",
        "which products can be returned",
        "what is the time limit on returns",
        "is fresh produce returnable",
        "what cannot be returned",
        "do I have to pay to return something",
        "tell me the rules around returning goods",
    ),
    "return_start": (
        "how do I start a return",
        "I want to return an item",
        "where do I request a return",
        "begin a return for my order",
        "I need to send something back",
        "how do I raise a return request",
        "set up a return for me",
        "I would like to return what I bought",
        "take this item back please",
    ),
    "return_status": (
        "what is the status of my return",
        "has my return been approved",
        "is my return request accepted",
        "any update on the return I raised",
        "where has my return got to",
        "did you receive the item I sent back",
        "has anyone reviewed my return yet",
        "my return has been pending for days",
        "progress on the return I opened",
    ),
    "refund_status": (
        "where is my refund",
        "has my refund been processed",
        "I have not received my refund yet",
        "what is the status of my refund",
        "when will my money come back",
        "my refund has not reached my account",
        "no refund credited so far",
        "chasing the refund you promised",
        "has the money been sent back to me",
    ),
    "refund_timing": (
        "how long does a refund take",
        "how many days for a refund to be credited",
        "what is the usual refund processing time",
        "when do refunds normally arrive",
        "typical turnaround on a refund",
        "how quickly is money returned after approval",
    ),
    "exchange_request": (
        "can I exchange this for something else",
        "I want a replacement instead of a refund",
        "do you do exchanges",
        "swap my item for a different one",
        "can I trade this for another product",
        "send a replacement rather than money back",
    ),
    # -------------------------------------------------------------- payments
    "payment_methods": (
        "what payment methods do you accept",
        "can I pay by upi",
        "do you take credit cards",
        "which cards are accepted",
        "how can I pay for my order",
        "do you support net banking",
        "is there a wallet option at checkout",
        "what ways can I pay you",
        "do you accept debit cards",
    ),
    "payment_failed": (
        "my payment failed",
        "the transaction did not go through",
        "payment keeps getting declined",
        "I cannot complete the payment",
        "checkout fails when I try to pay",
        "my card was rejected at checkout",
        "the payment page throws an error",
        "unable to pay for my basket",
        "payment gateway is not accepting my card",
    ),
    "payment_debited_no_order": (
        "money was deducted but no order was placed",
        "I was charged twice for one order",
        "amount debited but order not confirmed",
        "you took my money and there is no order",
        "double charged on my card",
        "payment left my account but nothing was confirmed",
        "two identical charges for a single purchase",
    ),
    "cod_availability": (
        "do you offer cash on delivery",
        "is cod available in my area",
        "can I pay when the order arrives",
        "do you accept cash at the door",
        "is pay on delivery an option",
    ),
    # ------------------------------------------------------------- catalogue
    "product_availability": (
        "is this product in stock",
        "do you have any left",
        "is it available right now",
        "can I still buy this",
        "do you sell fresh turmeric",
        "is this item out of stock",
        "do you stock organic rice",
        "have you got any in at the moment",
        "is that one available to order",
        "can I get hold of some today",
        "do you carry this product",
        "is there stock of the millet",
    ),
    "product_price": (
        "how much does this cost",
        "what is the price of this product",
        "how much for a kilo",
        "what does it sell for",
        "price list for your products",
        "what am I looking at price wise",
        "how much would a pack set me back",
        "what is the rate per kg",
    ),
    "product_restock": (
        "when will this be back in stock",
        "will you restock this item",
        "can you tell me when it is available again",
        "notify me when this comes back",
        "is this coming back",
        "any idea when you will have more",
        "when do you expect new stock in",
        "is it gone for good or returning",
    ),
    "product_storage": (
        "how should I store this",
        "what is the best way to keep this fresh",
        "does this need refrigeration",
        "how long will this keep",
        "storage instructions for this product",
        "shelf life of this item",
        "should this go in the fridge or the cupboard",
        "how do I stop this spoiling quickly",
        "can I freeze this",
    ),
    "product_sourcing": (
        "where does this product come from",
        "which farm grows this",
        "who produces this",
        "is this locally sourced",
        "tell me about the origin of this product",
        "what is the source of this item",
        "which region is this grown in",
        "who is the farmer behind this",
    ),
    "product_certification": (
        "is this certified organic",
        "what certifications do your products have",
        "do you have organic certification",
        "is this pesticide free",
        "are your farms certified",
        "what accreditation does this carry",
        "any lab certification for this product",
    ),
    "category_browse": (
        "what categories do you have",
        "show me your product range",
        "what do you sell",
        "what kinds of products are available",
        "browse your catalogue",
        "what is in your shop",
        "what sort of goods do you offer",
        "give me a list of your ranges",
    ),
    "bundle_info": (
        "do you sell combo packs",
        "what is in the bundle",
        "do you have gift hampers",
        "are there any product bundles",
        "any multipack or kit options",
        "do you sell sets of products together",
    ),
    # -------------------------------------------------------------- delivery
    "delivery_areas": (
        "do you deliver to my area",
        "which pin codes do you serve",
        "do you deliver in bangalore",
        "is my location serviceable",
        "what areas do you cover",
        "can you deliver to my pin code",
        "do you come out to my part of the city",
        "is delivery available at my address",
    ),
    "delivery_charges": (
        "how much is delivery",
        "what are the shipping charges",
        "is delivery free",
        "do I have to pay for shipping",
        "what is the minimum order for free delivery",
        "will I be charged extra for delivery",
        "any courier fee on top of the price",
    ),
    "delivery_time": (
        "how long does delivery take",
        "how many days for delivery",
        "what is the usual delivery time",
        "how quickly do you dispatch orders",
        "how soon can I expect a new order",
        "what is the turnaround on shipping",
        "how fast do orders normally arrive",
    ),
    "delivery_slots": (
        "can I choose a delivery slot",
        "what time will my order arrive",
        "do you deliver on sundays",
        "can I pick a delivery date",
        "what are your delivery timings",
        "is there a morning or evening option",
        "can I schedule when it comes",
        "do you deliver at the weekend",
    ),
    "pickup_points": (
        "can I collect my order myself",
        "where are your pickup points",
        "do you have a store I can visit",
        "is self collection possible",
        "can I fetch it from a depot",
        "any walk in collection option",
    ),
    "international_shipping": (
        "do you ship abroad",
        "can you deliver outside india",
        "do you offer international delivery",
        "can I order from overseas",
        "will you post to another country",
    ),
    # --------------------------------------------------------------- account
    "account_signin_problem": (
        "I cannot sign in to my account",
        "login is not working",
        "it says my credentials are wrong",
        "I am locked out of my account",
        "why can I not access my account",
        "sign in keeps failing for me",
        "my account will not let me in",
        "it rejects my details every time",
    ),
    "account_password_reset": (
        "I forgot my password",
        "how do I reset my password",
        "send me a password reset link",
        "I want to change my password",
        "recover my forgotten password",
        "set a new password on my account",
    ),
    "account_otp_not_received": (
        "I did not get the otp",
        "the verification code never arrived",
        "otp is not coming to my phone",
        "resend the verification code",
        "no sms with the code has reached me",
        "verification message is not showing up",
    ),
    "account_delete": (
        "delete my account",
        "I want my data removed",
        "close my account permanently",
        "remove all my personal information",
        "wipe my details from your system",
        "erase everything you hold on me",
    ),
    "account_change_contact": (
        "how do I change my email address",
        "update my phone number on my account",
        "I need to change my registered mobile",
        "edit my contact details",
        "my number has changed how do I update it",
    ),
    "account_addresses": (
        "how do I add a delivery address",
        "where do I manage my saved addresses",
        "edit the addresses on my account",
        "save a second address to my profile",
        "remove an old address from my account",
    ),
    "account_unsubscribe": (
        "stop sending me emails",
        "how do I unsubscribe from the newsletter",
        "I do not want marketing messages",
        "opt me out of your mailing list",
        "take me off your promotional list",
        "too many emails from you please stop",
    ),
    "account_register": (
        "how do I create an account",
        "do I need an account to order",
        "can I checkout as a guest",
        "sign me up",
        "is registration required to buy",
        "how do I join as a new customer",
    ),
    # -------------------------------------------------------------- programs
    "loyalty_points": (
        "how many points do I have",
        "what is my loyalty balance",
        "how do loyalty points work",
        "can I redeem my reward points",
        "check the points on my account",
        "what are my points worth",
    ),
    "referral_program": (
        "do you have a referral programme",
        "what is my referral code",
        "how do I invite a friend",
        "what do I get for referring someone",
        "share code for inviting friends",
    ),
    "giftcard_balance": (
        "what is the balance on my gift card",
        "how much is left on my voucher",
        "check my gift card value",
        "is my gift card still valid",
        "how much credit remains on this card",
    ),
    "giftcard_buy": (
        "can I buy a gift card",
        "do you sell gift vouchers",
        "how do I gift someone a card",
        "where do I redeem a gift card",
        "I want to purchase a voucher as a present",
        "how do I apply a gift card to an order",
    ),
    "discount_available": (
        "do you have any discount codes",
        "are there any offers running",
        "is there a sale on",
        "any promo code I can use",
        "first order discount",
        "what deals are live at the moment",
        "anything on special this week",
    ),
    "discount_not_working": (
        "my coupon code is not working",
        "the discount did not apply at checkout",
        "it says my promo code is invalid",
        "why was my voucher rejected",
        "the code will not go through on my basket",
        "discount is not showing on my total",
    ),
    "subscription_status": (
        "what is the status of my subscription",
        "when is my next subscription delivery",
        "show me my active subscriptions",
        "what am I subscribed to",
        "when does my repeat order go out",
    ),
    "subscription_manage": (
        "how do I pause my subscription",
        "cancel my recurring order",
        "can I skip the next delivery",
        "change the frequency of my subscription",
        "put my repeat order on hold",
        "stop my subscribe and save",
        "make my subscription monthly instead",
    ),
    "preorder_harvest": (
        "can I preorder the next harvest",
        "when is the next harvest",
        "how does preordering work",
        "when will the new crop be ready",
        "can I reserve some before it is picked",
        "when does the season start for this",
    ),
    "bulk_b2b": (
        "do you sell in bulk",
        "I want to place a wholesale order",
        "do you supply to restaurants",
        "can I get a business account",
        "bulk pricing for large quantities",
        "trade rates for a cafe",
        "corporate order for my company",
    ),
    # --------------------------------------------------------------- content
    "recipe_lookup": (
        "do you have any recipes",
        "what can I cook with this",
        "show me a recipe using your products",
        "recipe ideas please",
        "how do I cook this",
        "any dishes I can make with what you sell",
        "suggest something to make for dinner",
    ),
    "article_lookup": (
        "do you have a blog",
        "where can I read your articles",
        "any posts about farming",
        "show me your blog posts",
        "do you publish anything to read",
        "articles about your produce",
    ),
    "review_how_to": (
        "how do I leave a review",
        "where can I rate a product",
        "can I write a review for what I bought",
        "why has my review not appeared",
        "post feedback on something I ordered",
        "how do star ratings work here",
    ),
    "wishlist_how_to": (
        "how do I save items for later",
        "where is my wishlist",
        "can I add products to a favourites list",
        "bookmark a product for another time",
        "where did my saved products go",
    ),
    "community_discussions": (
        "do you have a community forum",
        "where can I ask other customers",
        "is there a discussion board",
        "can I talk to other buyers",
        "where do people post questions here",
    ),
    # --------------------------------------------------------------- company
    "about_company": (
        "tell me about true grit",
        "who are you as a company",
        "what does your business do",
        "what is your story",
        "what is this company about",
        "who runs this shop",
        "background on your business",
    ),
    "farm_partnership": (
        "I am a farmer and want to sell with you",
        "how do I become a partner farm",
        "can my farm join your platform",
        "I want to supply produce to you",
        "apply to list my farm with you",
        "I grow crops and would like to sell here",
    ),
    "careers": (
        "are you hiring",
        "do you have any job openings",
        "how do I apply for a job",
        "can I send you my resume",
        "any vacancies at your company",
        "looking for work with you",
    ),
    "press_media": (
        "I am a journalist with a question",
        "who handles your press enquiries",
        "can I interview your founder",
        "media enquiry about your company",
        "I write for a magazine and need a quote",
        "press contact for your brand",
    ),
    "contact_details": (
        "how do I contact you",
        "what is your phone number",
        "what is your email address",
        "where is your office located",
        "how do I reach your team",
        "best way to get in touch with support",
        "do you have a helpline",
    ),
    "privacy_policy": (
        "what is your privacy policy",
        "how do you use my personal data",
        "do you share my information with anyone",
        "how is my data protected",
        "what do you do with customer data",
        "do you sell my details to third parties",
        "how long do you keep my information",
    ),
    "terms_conditions": (
        "what are your terms and conditions",
        "where can I read your terms of service",
        "show me your legal terms",
        "link to your user agreement",
    ),
    "sourcing_standards": (
        "what are your sourcing standards",
        "how do you choose your farms",
        "what quality checks do you do",
        "how do you ensure produce is fresh",
        "what do you require of your growers",
        "how is quality controlled before shipping",
    ),
    # ---------------------------------------------------------------- social
    "greeting": (
        "hello",
        "hi there",
        "good morning",
        "good evening",
        "hey",
    ),
    "farewell": (
        "goodbye",
        "bye for now",
        "see you later",
        "that is all",
    ),
    "thanks": (
        "thank you",
        "thanks a lot",
        "that was helpful",
        "appreciate it",
    ),
    "affirm": (
        "yes",
        "yes please",
        "that is correct",
        "sounds good",
    ),
    "deny": (
        "no",
        "no thanks",
        "that is not right",
        "not really",
    ),
    "bot_identity": (
        "are you a real person",
        "am I talking to a bot",
        "who am I chatting with",
        "are you an ai",
    ),
    "capabilities": (
        "what can you help me with",
        "what questions can you answer",
        "what are you able to do for me",
    ),
    # ------------------------------------------------------- guard and human
    "human_handoff": (
        "I want to speak to a human",
        "connect me to an agent",
        "put me through to customer care",
        "can I talk to a real person",
        "this bot is not helping get me support",
        "escalate this to your team",
        "I need a member of staff",
    ),
    "complaint": (
        "this is terrible service",
        "I am very disappointed with you",
        "worst experience I have had",
        "I want to make a complaint",
        "you people are useless",
        "absolutely appalling way to treat a customer",
        "I am furious about how this was handled",
        "never ordering from you again",
    ),
    "legal_threat": (
        "I will take you to consumer court",
        "I am going to sue you",
        "my lawyer will contact you",
        "this is illegal and I will report you",
        "I am filing a case against your company",
    ),
    "safety_food": (
        "I got sick after eating your product",
        "this made me ill",
        "there was mould on the produce",
        "I had an allergic reaction to this",
        "I found something foreign in the packet",
        "the food smelled rotten and I ate it",
        "my child vomited after eating this",
        "there were insects inside the sealed pack",
        "the product tasted off and now I feel unwell",
    ),
    "medical_advice": (
        "is this safe for a diabetic",
        "can I eat this while pregnant",
        "will this help my blood pressure",
        "is this good for my condition",
        "does this cure anything",
        "is this suitable for someone with an allergy",
        "can my toddler eat this safely",
        "will this interact with my medication",
    ),
    "pii_request": (
        "give me the phone number of another customer",
        "show me your customer database",
        "what is the home address of your owner",
        "list the emails of people who ordered this",
    ),
    "fraud_scam": (
        "send my refund to this upi id instead",
        "I am from your bank team share the otp",
        "transfer the money to a different account",
        "give me a link to pay you directly",
    ),
    "off_topic": (
        "what is the weather today",
        "tell me a joke",
        "who won the cricket match",
        "write me a poem",
        "what is the capital of france",
        "help me with my homework",
        "what do you think about politics",
        "can you do maths for me",
    ),
}
